services:
  raiko:
    build:
      context: ..
      dockerfile: Dockerfile
    image: nethermind.jfrog.io/core-oci-local-staging/raiko:latest
    container_name: raiko
    command: --concurrency-limit=1
    env_file:
      - .env
    volumes:
      - /var/log/raiko:/var/log/raiko
      - ../host/config:/raiko/config
    ports:
      - "8080:8080"
    environment:
      - RAIKO_CONF_DIR=${RAIKO_CONF_DIR:-/raiko/config/devnet}
      - BASE_CONFIG_FILE=${BASE_CONFIG_FILE:-config.json}
      - BASE_CHAINSPEC_FILE=${BASE_CHAINSPEC_FILE:-chain_spec_list.json}
      - PREFETCH_CHUNK_SIZE=${PREFETCH_CHUNK_SIZE}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - RUST_LOG=${RUST_LOG:-info}
    depends_on:
      - redis
    profiles:
      - prod-redis
  redis:
    image: redis
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    profiles:
      - prod-redis
