[package]
name = "raiko-tdx"
version = "0.1.0"
edition = "2021"

[dependencies]
# Prover module
tdx-prover = { path = "prover", optional = true }

[features]
default = []
enable = ["dep:tdx-prover", "tdx-prover/enable"]