name: "[Nethermind] Raiko Client SGX - Docker build and push"

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v*-surge"
    paths:
      - "**"
      - "!docs/**"
      - "!img/**"
      - "!**/*.json"
      - "!**/README.md"
      - "!docker/**"
      - "!.github/**"
      - "host/config/chain_spec_list_default.json"
      - "!provers/sp1/**"
      - "!provers/risc0/**"

env:
  DOCKER_REGISTRY: nethermind.jfrog.io
  DOCKER_REPOSITORY_STAGING: core-oci-local-staging/raiko-sgx
  DOCKER_PUBLIC_REGISTRY: docker.io 
  DOCKER_PUBLIC_REPOSITORY: nethermind/raiko-sgx

jobs:
  build:
    name: Build and push docker image to Staging
    runs-on: ubuntu-latest
    if: github.repository == 'NethermindEth/raiko'
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            short: amd64

    outputs:
      digest-amd64: ${{ steps.digest.outputs.amd64 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_CORE_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_CORE_TOKEN_DEVELOPER }}

      - name: Determine build tags
        id: build-tags
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            # Remove -surge suffix if present
            BASE_VERSION=${VERSION%-surge}
            echo "tag_list=type=raw,value=latest,type=raw,value=$BASE_VERSION" >> $GITHUB_OUTPUT
          else
            echo "tag_list=type=raw,value=latest" >> $GITHUB_OUTPUT
          fi

      - name: Docker meta for staging
        id: meta-staging
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY_STAGING }}
          tags: ${{ steps.build-tags.outputs.tag_list }}

      - name: Build and push with tags
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta-staging.outputs.tags }}
          labels: ${{ steps.meta-staging.outputs.labels }}

      - name: Set digest output
        id: digest
        run: |
          echo "amd64=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY_STAGING }}@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  merge:
    name: Create manifest and promote to Production
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Setup ORAS
        uses: oras-project/setup-oras@v1

      - name: Check ORAS version
        run: oras version

      - name: Login to Artifactory registry with ORAS
        run: |
          oras login ${{ env.DOCKER_REGISTRY }} \
            -u ${{ secrets.ARTIFACTORY_CORE_USERNAME }} \
            -p ${{ secrets.ARTIFACTORY_CORE_TOKEN_DEVELOPER }}

      - name: Login to Dockerhub registry with ORAS
        run: |
          oras login ${{ env.DOCKER_PUBLIC_REGISTRY }} \
            -u ${{ secrets.DOCKER_HUB_USERNAME }} \
            -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Determine tags to promote
        id: promote-tags
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            BASE_VERSION=${VERSION%-surge}
            echo "TAGS=latest $BASE_VERSION" >> $GITHUB_ENV
          else
            echo "TAGS=latest" >> $GITHUB_ENV
          fi

      - name: Promote to Dockerhub Production
        run: |
          for tag in $TAGS; do
            echo "Current tag: $tag"
            source_image="${DOCKER_REGISTRY}/${DOCKER_REPOSITORY_STAGING}:${tag}"
            prod_image="${DOCKER_PUBLIC_REGISTRY}/${DOCKER_PUBLIC_REPOSITORY}:${tag}"
            echo "Promoting ${source_image} to ${prod_image}"
            oras cp -r "${source_image}" "${prod_image}"
          done

      - name: Summary
        run: |
          echo "## SGX Docker build completed ✅" >> $GITHUB_STEP_SUMMARY
          echo "### Tags" >> $GITHUB_STEP_SUMMARY
          for tag in $TAGS; do
            echo "- $tag" >> $GITHUB_STEP_SUMMARY
          done
          echo "### Notes" >> $GITHUB_STEP_SUMMARY
          echo "- The images have been pushed to ${DOCKER_REPOSITORY_STAGING} repo" >> $GITHUB_STEP_SUMMARY
          echo "- **STAGING Repository**: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY_STAGING }}" >> $GITHUB_STEP_SUMMARY
          echo "- **PROD Repository**: ${{ env.DOCKER_PUBLIC_REGISTRY }}/${{ env.DOCKER_PUBLIC_REPOSITORY }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Platforms**: linux/amd64" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
